export enum TaxReportDialogLabel {
  DropFilesHere = 'Drop files here...',
}

export enum TaxReportDialogError {
  NoFiscalYearProvided = 'No fiscal year provided. Please select a valid fiscal year',
  NoFiscalQuarterProvided = 'No fiscal quarter provided. Please select a valid fiscal quarter',
  NoFileDestinationProvided = 'No file destination provided. Please provide a valid file destination',
  NoFileProvided = 'No file provided. Please provide Excel Workbook file generated by QuickBooks Desktop Pro',
  UnsupportedFileProvided = 'Unsupported file provided. Please provide Excel Workbook file generated by QuickBooks Desktop Pro.',
}
