export enum TaxReportDialogLabel {
  DropFilesHere = 'Drop files here...',
}

export enum TaxReportDialogError {
  NoFileProvided = 'No file provided. Please provide Excel Workbook file generated by QuickBooks Desktop Pro',
  UnsupportedFileProvided = 'Unsupported file provided. Please provide Excel Workbook file generated by QuickBooks Desktop Pro.',
}
