on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy"
        type: string
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci

      - name: Build app
        run: |
          if [[ ${{ inputs.environment  }} == "Production" ]]
          then
            npm run build:prod
          else
            npm run build:dev
          fi

      - name: SCP to server & Deploy app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TAX_REPORT_HOSTNAME }}
          username: ${{ secrets.TAX_REPORT_SSH_USERNAME }}
          password: ${{ secrets.TAX_REPORT_SSH_PASSWORD }}
          port: ${{ secrets.TAX_REPORT_SSH_PORT }}
          source: "dist/tax-report"
          target: ${{ secrets.TAX_REPORT_DEPLOY_DIRECTORY }}
          rm: true # Remove target folder before upload data
          strip_components: 2
